import Head from 'next/head'
import Link from 'next/link'
import { Tab } from '@headlessui/react'
import Masonry from 'react-masonry-css'
import classNames from 'classnames'
import Image from 'next/image'
import bgImage from '../public/ocean.jpg'

import ocean1 from '../public/1.jpg'
import ocean2 from '../public/2.jpg'
import ocean3 from '../public/3.jpg'
import ocean4 from '../public/gtr.jpg'

const tabs = [
	{
		key: 'all',
		display: 'All',
	},
	{
		key: 'oceans',
		display: 'Oceans',
	},
	{
		key: 'forests',
		display: 'Forests',
	},
]

const images = [ocean1, ocean2, ocean3, ocean4]

export default function Home() {
	return (
		<div className='h-full  overflow-auto'>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Image
				className='fixed left-0 top-0 z-0'
				src={bgImage}
				alt='placeholder-img'
				placeholder='blur'
			/>

			<div className='fixed left-0 top-0 w-full h-ful z-10 from-stone-900 bg-gradient-to'></div>

			<header className='fixed bg-black top-0 flex w-full z-20  justify-between items-center h-[90px] px-10'>
				<span className='uppercase text-lg font-medium'>
					Photography Portfolio
				</span>
				<Link
					href='#'
					className='rounded-xl bg-white text-stone-700 px-3 py-2 hover:bg-opacity-90'
				>
					Get in touch
				</Link>
			</header>

			<main className='relative pt-[110px] z-20'>
				<div className='flex flex-col items-center h-full'>
					<Tab.Group>
						<Tab.List className='flex items-center gap-12'>
							{tabs.map(tab => (
								<Tab key={tab.key} className='p-2'>
									{({ selected }) => (
										<span
											className={classNames(
												'uppercase text-lg',
												selected ? 'text-stone-400' : 'text-white'
											)}
										>
											{tab.display}
										</span>
									)}
								</Tab>
							))}
						</Tab.List>
						<Tab.Panels className='  h-full  max-w-[900px] w-full p-2 sm:p-4 my-6'>
							<Tab.Panel className='overflow-auto'>
								<Masonry
									breakpointCols={2}
									className='flex gap-4'
									columnClassName=''
								>
									{images.map(image => (
										<Image
											key={image.src}
											src={image}
											alt='placeholder'
											className='my-4 '
											placeholder='blur'
										/>
									))}
								</Masonry>
							</Tab.Panel>
							<Tab.Panel>Oceans</Tab.Panel>
							<Tab.Panel>Forests</Tab.Panel>
						</Tab.Panels>
					</Tab.Group>
				</div>
			</main>

			<footer className='relative h-[60px] flex justify-center items-center uppercase text-lg z-20'>
				Placeholder for footer
			</footer>
		</div>
	)
}
