import Head from 'next/head'
import Link from 'next/link'
import { Tab } from '@headlessui/react'
import Masonry from 'react-masonry-css'

const tabs = [
	{
		key: 'all',
		display: 'All',
	},
	{
		key: 'oceans',
		display: 'Oceans',
	},
	{
		key: 'forests',
		display: 'Forests',
	},
]

export default function Home() {
	return (
		<div className="h-full bg-[url('/ocean.jpg')] bg-bottom bg-cover overflow-auto">
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<header className='fixed bg-black top-0 flex w-full z-10  justify-between items-center h-[90px] px-6'>
				<div>Photography Portfolio</div>
				<Link
					href='#'
					className='rounded-xl bg-white text-stone-700 px-3 py-2 hover:bg-opacity-90'
				>
					Get in touch
				</Link>
			</header>

			<main className='pt-[110px]'>
				<div className='flex flex-col items-center h-full'>
					<Tab.Group>
						<Tab.List className='flex items-center gap-12'>
							{tabs.map(tab => (
								<Tab key={tab.key} className='p-2'>
									{({ selected }) => (
										<span
											className={selected ? 'text-white' : 'text-stone-600'}
										>
											{tab.display}
										</span>
									)}
								</Tab>
							))}
						</Tab.List>
						<Tab.Panels className='  h-full  max-w-[900px] w-full p-2 sm:p-4 my-6'>
							<Tab.Panel className='overflow-auto'>
								<Masonry
									breakpointCols={2}
									className='flex gap-2'
									columnClassName=''
								>
									<img src='/1.jpg' alt='1' className='my-2' />
									<img src='/2.jpg' alt='2' className='my-2' />
									<img src='/3.jpg' alt='3' className='my-2' />
									<img src='/lambo.jpg' alt='3' className='my-2' />
								</Masonry>
							</Tab.Panel>
							<Tab.Panel>Oceans</Tab.Panel>
							<Tab.Panel>Forests</Tab.Panel>
						</Tab.Panels>
					</Tab.Group>
				</div>
			</main>

			<footer className='h-[60px] flex justify-center items-center'>
				Placeholder for footer
			</footer>
		</div>
	)
}
